name: Antimony CICD
run-name: ${{ github.actor }} is running CICD Pipelines
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # This is for the frontend unit tests
  frontend-unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and Run webpack 🔧
        run: |
          cd vscode-antimony/
          npm install
          npm run webpack

      # - name: Test 🚨
      #   run: npm test

  # This is for the backend unit tests
  backend-unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pytest
          cd vscode-antimony/
          pip3 install git+https://github.com/lark-parser/lark.git@5b8c04ca83b9#egg=lark_parser
          python3 -m pip --disable-pip-version-check install -t ./pythonFiles/lib/python --no-cache-dir --upgrade -r ./all-requirements.txt && success=1
          pip3 install antimony
          #if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          cd vscode-antimony/src/server/stibium/test/
          pip3 install requests
          pip3 install bioservices
          pip3 install pygls
          python3 -m pytest test_grammar.py
          python3 -m pytest test_diagnostics.py
          python3 -m pytest test_error_recovery.py
          python3 -m pytest test_parser.py
          python3 -m pytest test_completion.py
          cd import-test-data/
          python3 -m pytest test_import.py
